[meta]
name = "Better Chat"
author = "Miss"
category = "Better Suite"

siteid = 134
version = "0.3.0"

[script]
dependencies = [ "NadeoServices" ]
imports = [ "Icons.as", "Formatting.as", "Permissions.as", "Time.as" ]
timeout = 0
