[meta]
name = "Better Chat"
author = "Miss"
category = "Better Suite"
version = "1.1.4"

[script]
optional_dependencies = [ "NadeoServices" ]

exports = [ "src/Export.as" ]
shared_exports = [ "src/ExportShared.as" ]

timeout = 0
